### ISSUE TITLE
Not working with Chinese text

### ISSUE THREAD

**Issue by wstlxx** [travisvn/openai-edge-tts#1]
So my setup is tested within open web UI, working with English text for sure.
when it comes to Chinese, it gives External: 500 Server Error: INTERNAL SERVER ERROR for url: http://myipaddress:5050/v1/audio/speech

Also, the reason why I didn't use localhost, it somehow did not point to the local tts service from openwebui, and I had to use the external public IP address instead which isn't a big issue and probably an openwebui side problem.

Other than that, it works like a charm.

**Comment by travisvn** [comment]
Hello @wstlxx 

After seeing your opened issue, I tested the API endpoint with a non-Latin alphabet language and chose a sentence in Japanese. 

It's possible you're getting the error due to encoding issues with how the call is made — I am not sure of your scenario. But when testing the API, running this curl command worked exactly as expected: 

```bash
curl -X POST http://localhost:5050/v1/audio/speech \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer your_api_key_here" \
  -d '{
    "model": "tts-1",
    "input": "じゃあ、行く。電車の時間、調べておくよ。",
    "voice": "ja-JP-KeitaNeural"
  }' \
  --output speech.mp3
```

Maybe you did not select a Chinese voice to accompany your request. 

There are several Chinese voices which can be viewed by a few different methods. The easiest in my opinion is to install `edge-tts` on your machine and run `edge-tts --list-voices`. 

However, I went ahead and revamped the API endpoints for this project to more easily return localized voices. 

Here's the commit that includes all of the points I'm about to list below: https://github.com/travisvn/openai-edge-tts/commit/0ff53edcb59f1c129f98fb2cf76d38780a58c8f2 

1. There is now an option to forego requiring an API key. This allows for easier calls, as you can visit `http://localhost:5050/v1/voices` in your browser URL bar if you've set the environment variable to not require an API key. 
2. The `/v1/voices` endpoint now accepts and correctly filters voices when provided a `language` or `locale` attribute in the request (be it though URL search parameters or a JSON request body). You'll want to set locale to one of the `zh-` variants (`zh-CN`, `zh-HK`, or `zh-TW`)

I have not updated the README — I came here to let you know first. 

On that note, I have not pushed this update to the Docker Hub, so you won't be able to use this updated version if you're running straight through with something like `docker run`. Follow the Python instructions in the README to be able to dynamically set things up and test it all out. 

In the interim, you should be able to generate Chinese TTS if you set the voice properly. So selecting one of the voices below should solve your problem:

> Name: zh-CN-XiaoxiaoNeural
> Gender: Female
> 
> Name: zh-CN-XiaoyiNeural
> Gender: Female
> 
> Name: zh-CN-YunjianNeural
> Gender: Male
> 
> Name: zh-CN-YunxiNeural
> Gender: Male
> 
> Name: zh-CN-YunxiaNeural
> Gender: Male
> 
> Name: zh-CN-YunyangNeural
> Gender: Male
> 
> Name: zh-CN-liaoning-XiaobeiNeural
> Gender: Female
> 
> Name: zh-CN-shaanxi-XiaoniNeural
> Gender: Female
> 
> Name: zh-HK-HiuGaaiNeural
> Gender: Female
> 
> Name: zh-HK-HiuMaanNeural
> Gender: Female
> 
> Name: zh-HK-WanLungNeural
> Gender: Male
> 
> Name: zh-TW-HsiaoChenNeural
> Gender: Female
> 
> Name: zh-TW-HsiaoYuNeural
> Gender: Female
> 
> Name: zh-TW-YunJheNeural
> Gender: Male

-Travis

**Comment by a506488043** [comment]
> 你好[@wstlxx](https://github.com/wstlxx)
> 
> 在看到您提出的问题后，我使用非拉丁字母语言测试了 API 端点，并选择了一句日语句子。
> 
> 您可能是因为调用方式的编码问题而遇到此错误——我不确定您的具体情况。但在测试 API 时，运行以下 curl 命令完全符合预期：
> 
> curl -X POST http://localhost:5050/v1/audio/speech \
>   -H "Content-Type: application/json" \
>   -H "Authorization: Bearer your_api_key_here" \
>   -d '{
>     "model": "tts-1",
>     "input": "じゃあ、行く。電車の時間、調べておくよ。",
>     "voice": "ja-JP-KeitaNeural"
>   }' \
>   --output speech.mp3
> 也许您没有选择中文语音来发送您的请求。
> 
> 有几种中文语音包可以通过几种不同的方法查看。在我看来，最简单的方法是`edge-tts`在你的电脑上安装并运行`edge-tts --list-voices`。
> 
> 不过，我还是着手改进了这个项目的 API 端点，以便更轻松地返回本地化语音。
> 
> 以下是包含我即将列出的所有要点的提交：[0ff53ed](https://github.com/travisvn/openai-edge-tts/commit/0ff53edcb59f1c129f98fb2cf76d38780a58c8f2)
> 
> 1. 现在可以选择不输入 API 密钥。这样一来，调用就更方便了，`http://localhost:5050/v1/voices`如果您已设置环境变量使其不需要 API 密钥，则可以直接在浏览器地址栏中访问。
> 2. 现在，该`/v1/voices`端点可以接受并正确过滤请求中提供的语音`language`（`locale`无论是通过 URL 搜索参数还是 JSON 请求正文）。您需要将区域设置设为以下`zh-`变体之一（`zh-CN`、、`zh-HK`或`zh-TW`）。
> 
> 我还没有更新 README 文件——我来这里是为了第一时间通知大家。
> 
> 需要注意的是，我尚未将此更新推送至 Docker Hub，因此如果您直接使用类似 `docker build` 的工具，则无法使用此更新版本`docker run`。请按照 README 文件中的 Python 说明进行操作，以便动态设置并进行测试。
> 
> 在此期间，如果您正确设置语音，应该可以生成中文文本转语音 (TTS)。因此，选择以下语音之一应该可以解决您的问题：
> 
> > 姓名：zh-CN-XiaoxiaoNeural
> > 性别：女
> > 姓名：zh-CN-XiaoyiNeural
> > 性别：女
> > 姓名：zh-CN-YunjianNeural
> > 性别：男
> > 姓名：zh-CN-YunxiNeural
> > 性别：男
> > 姓名：zh-CN-YunxiaNeural
> > 性别：男
> > 姓名：zh-CN-YunyangNeural
> > 性别：男
> > 姓名：zh-CN-辽宁-小北神经
> > 性别：女
> > 姓名：zh-CN-shaanxi-XiaoniNeural
> > 性别：女
> > 姓名：zh-HK-HiuGaaiNeural
> > 性别：女
> > 姓名：zh-HK-HiuMaanNeural
> > 性别：女
> > 姓名：zh-HK-WanLungNeural
> > 性别：男
> > 姓名：zh-TW-HsiaoChenNeural
> > 性别：女
> > 姓名：zh-TW-HsiaoYuNeural
> > 性别：女
> > 姓名：zh-TW-YunJheNeural
> > 性别：男
> 
> 特拉维斯

设置了还是，不支持中文啊
