### ISSUE TITLE
Incorrect CMD Path in Dockerfile Causes App to Fail on Startup

### ISSUE THREAD

**Issue by Gerkinfeltser** [travisvn/openai-edge-tts#5]
Hello,

I encountered an issue when attempting to run the project using Docker Compose. The app fails to start due to an incorrect path specified in the `CMD` directive in the `Dockerfile`. The `server.py` file is located in the `app/` directory within `/app`, but the current `CMD` is referencing the root `/app` directory. This results in the following error:

```
python: can't open file '/app/server.py': [Errno 2] No such file or directory
```

### Steps to Reproduce:
1. Clone the repository.
2. Run `docker-compose up --build`.
3. The container exits with the error mentioned above.

### Proposed Fix:
Modify the `CMD` directive in the `Dockerfile` to point to the correct path:
```dockerfile
CMD ["python", "app/server.py"]
```

This adjustment resolves the issue and allows the app to run correctly. Also, FWIW I'm on windows 10.

Thank you for your work on this project! Please let me know if any additional details are needed.

**Comment by travisvn** [comment]
@Gerkinfeltser Spooky timing — I've finally come around to working on a fix right before you posted this issue..! (I'd been putting it off for a week or two)

Hopefully will have the update out soon. Appreciate the detailed report 👍

**Comment by travisvn** [comment]
Aaaaand it's done! https://github.com/travisvn/openai-edge-tts/commit/d22b06af87e3b84c27768c9b43d8c738dddddd13

Go ahead and give it a try now. 

Note: make sure to use `docker compose` instead of `docker-compose`. The latter is an older version of docker compose, and the supplied `docker-compose.yml` file is designed for V2 (`docker compose`)


So to get things started fresh, 
```bash
git clone https://github.com/travisvn/openai-edge-tts.git
cd openai-edge-tts

cp .env.example .env
docker compose up --build
```

And then if you want to run it in the background, exit out of that instance and run with:

```bash
docker compose up -d
```

Hope you get it working!

**Comment by Gerkinfeltser** [comment]
Works great! Thank you for the quick resolution (& psychic harmonizing 😛)
